### ISSUE TITLE
Novoda open source heading

### ISSUE THREAD

**Issue by MechaRyRy** [novoda/novoda.github.io#10]
### Problem 
The Open-source introduction feels short, it doesn't really justify the way we feel with examples. It doesn't show passion in my opinion.
![screen shot 2017-12-12 at 12 10 18](https://user-images.githubusercontent.com/3380092/33883898-7f64bb8a-df35-11e7-8a2f-d2bffc498463.png)

### Solution
This may require some consideration but take our [case studies](https://www.novoda.com/casestudy-immoscout), we should be showing the same dedication to the introduction on the Open-source page as we do there. We should try and get others involved not just the engineering team.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
