### ISSUE TITLE
NOS, engineering only?

### ISSUE THREAD

**Issue by MechaRyRy** [novoda/novoda.github.io#11]
### Problem
The NOS landing page feels like it is just for engineers. We have other great teams at Novoda including design, product and agile companions and we don't show their contributions to open-source on here. 

### Solution
Open-source is driven by this idea of free software. I don't feel this page is inclusive to others at Novoda and should be repurposed to show the contributions that other teams make too.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
