### ISSUE TITLE
Can you add some license for this repository ?

### ISSUE THREAD

**Issue by ravpacheco** [novoda/novoda.github.io#3]
Hello guys, congrats for your job, you have some great code.

I found your http://novoda.github.io/ page awesome and I want know if I can use the same web page skeleton ?
Can you add some formal license on this repository ?

Thanks guys

**Comment by ravpacheco** [comment]
Hello guys,

I have created a pull request adding Apache 2.0 license.

https://github.com/novoda/novoda.github.io/pull/4

I chose this license because another novoda repositories already use them

Can you accept ?
Thanks!

**Comment by blundell** [comment]
fixed by #4
