### ISSUE TITLE
First Issue link only points to one repo

### ISSUE THREAD

**Issue by MechaRyRy** [novoda/novoda.github.io#8]
### Problem 
The link shown below only points through to a single repository 😬  
![screen shot 2017-12-12 at 11 58 34](https://user-images.githubusercontent.com/3380092/33883485-dc701eca-df33-11e7-8d5f-c3e95f87c286.png)

### Solution
It would be better to link through to all of our currently open issues that are for beginners, GH introduced `good first issue` as a default label a little while ago, we could use that. 

https://github.com/search?utf8=%E2%9C%93&q=org%3Anovoda+is%3Aissue+label%3A%22good+first+issue%22+is%3Aopen&type=

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
