### ISSUE TITLE
NOS page headings

### ISSUE THREAD

**Issue by MechaRyRy** [novoda/novoda.github.io#9]
### Problem
The headings, shown below, whilst useful for `Novoda` are probably not useful for the average consumer of the webpage. Someone wanting to know about `Novoda`s open source contributions are more likely to want to see examples of where we have done `video playback`, `custom view based libraries`, `gradle plugins` etc. 

![screen shot 2017-12-12 at 12 06 50](https://user-images.githubusercontent.com/3380092/33883769-0671e018-df35-11e7-93e8-23f0048f460f.png)

### Solution
The headings need to be tailored more to interests than executing lifecycle.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
